version: '3'
services:
  redis:
    image: "redis:alpine"
    hostname: redis
  web:
    build: .
    ports:
      - "3001:3001"
    links:
     - redis:redis
    command: ["npm", "start"]

networks:
  redis-net:

volumes:
  redis-data: